name: Build Anaconda3 amazonlinux Image
on:
  push:
    branches:
      - main
    tags:
      - 'anaconda3-*'
    paths:
      - 'anaconda3/amazonlinux/Dockerfile'
      - '.github/workflows/anaconda_amazonlinux_ci.yml'
  pull_request:
    paths:
      - 'anaconda3/amazonlinux/Dockerfile'
      - '.github/workflows/anaconda_amazonlinux_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Login to DockerHub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3
        with:
          platforms: linux/arm64/v8

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5
        with:
          images: |
            continuumio/anaconda3
          tags: |
            type=ref,event=branch,suffix=-amazonlinux
            type=ref,event=pr,suffix=-amazonlinux
            type=match,pattern=anaconda3-(.*),group=1,suffix=-amazonlinux
          flavor: |
            latest=false

      - name: build-push anaconda3/amazonlinux
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5
        with:
          context: ./anaconda3/amazonlinux
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda3/amazonlinux/Dockerfile
          platforms: linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}
